/**
 * Generated TypeScript Types from GraphQL Schema
 * Auto-generated by @graphql-codegen
 */

// ============================================================================
// Scalars
// ============================================================================

export type UUID = string;
export type DateTime = string;
export type JSON = Record<string, unknown>;

// ============================================================================
// Anti-Masking Context Types
// ============================================================================

export type CallStatus = 'RINGING' | 'ACTIVE' | 'COMPLETED' | 'FAILED' | 'BLOCKED';
export type FraudType = 'CLI_MASKING' | 'SIMBOX' | 'WANGIRI' | 'IRSF' | 'PBX_HACKING';
export type Severity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type AlertStatus = 'PENDING' | 'ACKNOWLEDGED' | 'INVESTIGATING' | 'RESOLVED' | 'REPORTED_NCC';
export type ResolutionType = 'CONFIRMED_FRAUD' | 'FALSE_POSITIVE' | 'ESCALATED' | 'WHITELISTED';
export type GatewayType = 'LOCAL' | 'INTERNATIONAL' | 'TRANSIT';

export interface Carrier {
    id: UUID;
    code: string;
    name: string;
    countryCode: string;
    prefixes: string[];
    isActive: boolean;
    createdAt: DateTime;
    updatedAt: DateTime;
}

export interface Gateway {
    id: UUID;
    name: string;
    ipAddress: string;
    carrierId?: UUID;
    carrierName?: string;
    gatewayType: GatewayType;
    isActive: boolean;
    isBlacklisted: boolean;
    blacklistReason?: string;
    fraudThreshold: number;
    cpmLimit: number;
    acdThreshold: number;
    totalCalls: number;
    fraudCalls: number;
    createdAt: DateTime;
    updatedAt: DateTime;
    carrier?: Carrier;
}

export interface Call {
    id: UUID;
    callId?: string;
    aNumber: string;
    bNumber: string;
    sourceIp: string;
    gatewayId?: UUID;
    status: CallStatus;
    isFlagged: boolean;
    maskingDetected: boolean;
    confidenceScore?: number;
    alertId?: UUID;
    startedAt: DateTime;
    endedAt?: DateTime;
    durationSeconds?: number;
    createdAt: DateTime;
    gateway?: Gateway;
    alert?: FraudAlert;
}

export interface FraudAlert {
    id: UUID;
    bNumber: string;
    fraudType: FraudType;
    score: number;
    severity: Severity;
    distinctCallers: number;
    aNumbers: string[];
    sourceIps: string[];
    status: AlertStatus;
    acknowledgedBy?: string;
    acknowledgedAt?: DateTime;
    resolvedBy?: string;
    resolvedAt?: DateTime;
    resolution?: ResolutionType;
    resolutionNotes?: string;
    nccReported: boolean;
    nccReportId?: string;
    detectedAt: DateTime;
    updatedAt: DateTime;
    calls?: Call[];
}

export interface DashboardSummary {
    totalCalls24h: number;
    totalAlerts24h: number;
    pendingAlerts: number;
    criticalAlerts: number;
    resolvedAlerts24h: number;
    fraudRate: number;
    topGateways: GatewayStats[];
}

export interface GatewayStats {
    gateway: Gateway;
    totalCalls: number;
    fraudCalls: number;
    fraudRate: number;
}

// ============================================================================
// Remittance Context Types
// ============================================================================

export type TransferStatus =
    | 'PENDING'
    | 'AWAITING_PAYMENT'
    | 'PAYMENT_RECEIVED'
    | 'PROCESSING'
    | 'SENT_TO_BANK'
    | 'COMPLETED'
    | 'FAILED'
    | 'REFUNDED'
    | 'CANCELLED';

export type TransferPurpose =
    | 'FAMILY_SUPPORT'
    | 'EDUCATION'
    | 'MEDICAL'
    | 'INVESTMENT'
    | 'PROPERTY'
    | 'BUSINESS'
    | 'SAVINGS'
    | 'OTHER';

export interface RemittanceCorridor {
    id: UUID;
    sourceCountry: string;
    destinationCountry: string;
    sourceCurrency: string;
    destinationCurrency: string;
    exchangeRate: number;
    feeStructure: FeeStructure;
    minAmount: number;
    maxAmount: number;
    processingTimeHours: number;
    isActive: boolean;
}

export interface FeeStructure {
    flatFee: number;
    percentageFee: number;
    minFee: number;
    maxFee?: number;
}

export interface NigerianBank {
    id: UUID;
    code: string;
    name: string;
    shortName?: string;
    isActive: boolean;
    supportsInstantTransfer: boolean;
}

export interface Beneficiary {
    id: UUID;
    userId: UUID;
    firstName: string;
    lastName: string;
    middleName?: string;
    relationship?: string;
    bankCode: string;
    accountNumber: string;
    accountName?: string;
    isVerified: boolean;
    phoneNumber?: string;
    email?: string;
    isFavorite: boolean;
    createdAt: DateTime;
    bank?: NigerianBank;
}

export interface RemittanceTransaction {
    id: UUID;
    reference: string;
    senderId: UUID;
    beneficiaryId: UUID;
    corridorId: UUID;
    amountSent: number;
    currencySent: string;
    amountReceived: number;
    currencyReceived: string;
    exchangeRate: number;
    feeAmount: number;
    totalPaid: number;
    recipientBankCode: string;
    recipientAccountNumber: string;
    recipientAccountName?: string;
    status: TransferStatus;
    purpose: TransferPurpose;
    narration?: string;
    initiatedAt: DateTime;
    completedAt?: DateTime;
    failedAt?: DateTime;
    failureReason?: string;
    beneficiary?: Beneficiary;
    corridor?: RemittanceCorridor;
}

// ============================================================================
// Marketplace Context Types
// ============================================================================

export type ListingStatus = 'DRAFT' | 'ACTIVE' | 'PAUSED' | 'SOLD' | 'EXPIRED';
export type PricingType = 'FIXED' | 'HOURLY' | 'DAILY' | 'NEGOTIABLE' | 'QUOTE';
export type OrderStatus =
    | 'INQUIRY'
    | 'QUOTED'
    | 'PENDING_PAYMENT'
    | 'PAID'
    | 'IN_PROGRESS'
    | 'DELIVERED'
    | 'COMPLETED'
    | 'DISPUTED'
    | 'CANCELLED'
    | 'REFUNDED';

export interface ServiceCategory {
    id: UUID;
    code: string;
    name: string;
    description?: string;
    icon?: string;
    parentId?: UUID;
    displayOrder: number;
    isActive: boolean;
}

export interface NigerianState {
    id: UUID;
    code: string;
    name: string;
    capital?: string;
    region?: string;
}

export interface ProviderProfile {
    id: UUID;
    userId: UUID;
    businessName: string;
    businessType?: string;
    description?: string;
    logoUrl?: string;
    stateId?: UUID;
    city?: string;
    verificationStatus: string;
    tier: string;
    averageRating: number;
    totalReviews: number;
    totalOrders: number;
    isActive: boolean;
    state?: NigerianState;
}

export interface MarketplaceListing {
    id: UUID;
    providerId: UUID;
    categoryId: UUID;
    title: string;
    slug: string;
    description: string;
    features: string[];
    pricingType: PricingType;
    priceNgn?: number;
    priceMinNgn?: number;
    priceMaxNgn?: number;
    stateId?: UUID;
    city?: string;
    isRemoteAvailable: boolean;
    isDiasporaFriendly: boolean;
    images: string[];
    status: ListingStatus;
    isFeatured: boolean;
    viewCount: number;
    orderCount: number;
    publishedAt?: DateTime;
    createdAt: DateTime;
    provider?: ProviderProfile;
    category?: ServiceCategory;
    state?: NigerianState;
}

export interface MarketplaceOrder {
    id: UUID;
    reference: string;
    listingId?: UUID;
    providerId: UUID;
    customerId: UUID;
    status: OrderStatus;
    requirements?: string;
    quotedAmount?: number;
    agreedAmount?: number;
    currency: string;
    deliveryDate?: DateTime;
    deliveredAt?: DateTime;
    customerRating?: number;
    customerReview?: string;
    createdAt: DateTime;
    listing?: MarketplaceListing;
    provider?: ProviderProfile;
}

// ============================================================================
// Identity Context Types
// ============================================================================

export type UserRole = 'USER' | 'PROVIDER' | 'ANALYST' | 'ADMIN' | 'SUPER_ADMIN';
export type UserStatus = 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'DEACTIVATED';
export type KYCLevel = 'NONE' | 'BASIC' | 'INTERMEDIATE' | 'FULL';

export interface User {
    id: UUID;
    email: string;
    firstName: string;
    lastName: string;
    displayName?: string;
    avatarUrl?: string;
    role: UserRole;
    status: UserStatus;
    kycLevel: KYCLevel;
    createdAt: DateTime;
    updatedAt: DateTime;
}

export interface AuthPayload {
    accessToken: string;
    refreshToken: string;
    expiresAt: DateTime;
    user: User;
}

// ============================================================================
// Input Types
// ============================================================================

export interface AcknowledgeAlertInput {
    alertId: UUID;
}

export interface ResolveAlertInput {
    alertId: UUID;
    resolution: ResolutionType;
    notes?: string;
}

export interface CreateGatewayInput {
    name: string;
    ipAddress: string;
    carrierName: string;
    gatewayType: GatewayType;
    fraudThreshold?: number;
    cpmLimit?: number;
    acdThreshold?: number;
}

export interface UpdateGatewayInput {
    name?: string;
    fraudThreshold?: number;
    cpmLimit?: number;
    acdThreshold?: number;
}

export interface InitiateTransferInput {
    beneficiaryId: UUID;
    amount: number;
    currency: string;
    purpose: TransferPurpose;
    narration?: string;
}

export interface CreateBeneficiaryInput {
    firstName: string;
    lastName: string;
    middleName?: string;
    relationship?: string;
    bankCode: string;
    accountNumber: string;
    phoneNumber?: string;
    email?: string;
}

// ============================================================================
// Filter Types
// ============================================================================

export interface AlertFilters {
    status?: AlertStatus;
    severity?: Severity;
    fraudType?: FraudType;
    dateRange?: {
        start: DateTime;
        end: DateTime;
    };
}

export interface TransactionFilters {
    status?: TransferStatus;
    beneficiaryId?: UUID;
    dateRange?: {
        start: DateTime;
        end: DateTime;
    };
}

export interface ListingFilters {
    categoryId?: UUID;
    stateId?: UUID;
    status?: ListingStatus;
    pricingType?: PricingType;
    minPrice?: number;
    maxPrice?: number;
}
