-- Sentinel Anti-Call Masking Engine Database Migration
-- Version: 1.0.0
-- Description: Creates tables for CDR batch processing, pattern detection, and alert management

-- Table 1: call_records
-- Stores historical call detail records for batch analysis
CREATE TABLE IF NOT EXISTS call_records (
    id SERIAL PRIMARY KEY,
    call_timestamp TIMESTAMP NOT NULL,
    caller_number VARCHAR(20) NOT NULL,
    callee_number VARCHAR(20) NOT NULL,
    duration_seconds INTEGER NOT NULL,
    call_direction VARCHAR(10),
    termination_cause VARCHAR(50),
    location_code VARCHAR(10),
    processed_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for call_records
CREATE INDEX IF NOT EXISTS idx_caller_timestamp ON call_records(caller_number, call_timestamp);
CREATE INDEX IF NOT EXISTS idx_callee ON call_records(callee_number);
CREATE INDEX IF NOT EXISTS idx_timestamp ON call_records(call_timestamp);

-- Table 2: suspicious_patterns
-- Stores detected suspicious calling patterns
CREATE TABLE IF NOT EXISTS suspicious_patterns (
    id SERIAL PRIMARY KEY,
    pattern_type VARCHAR(50) NOT NULL,
    suspect_number VARCHAR(20) NOT NULL,
    detection_timestamp TIMESTAMP DEFAULT NOW(),
    confidence_score FLOAT NOT NULL,
    metadata JSONB
);

-- Indexes for suspicious_patterns
CREATE INDEX IF NOT EXISTS idx_suspect_number ON suspicious_patterns(suspect_number);
CREATE INDEX IF NOT EXISTS idx_pattern_type ON suspicious_patterns(pattern_type);
CREATE INDEX IF NOT EXISTS idx_detection_timestamp ON suspicious_patterns(detection_timestamp);

-- Table 3: sentinel_fraud_alerts
-- Stores fraud alerts generated by detection rules
CREATE TABLE IF NOT EXISTS sentinel_fraud_alerts (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL,
    suspect_number VARCHAR(20) NOT NULL,
    alert_severity VARCHAR(20) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    evidence_summary TEXT NOT NULL,
    call_count INTEGER,
    unique_destinations INTEGER,
    avg_duration_seconds FLOAT,
    detection_rule VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW(),
    reviewed BOOLEAN DEFAULT FALSE,
    reviewer_notes TEXT
);

-- Indexes for sentinel_fraud_alerts
CREATE INDEX IF NOT EXISTS idx_suspect ON sentinel_fraud_alerts(suspect_number);
CREATE INDEX IF NOT EXISTS idx_severity ON sentinel_fraud_alerts(alert_severity);
CREATE INDEX IF NOT EXISTS idx_created ON sentinel_fraud_alerts(created_at);
CREATE INDEX IF NOT EXISTS idx_reviewed ON sentinel_fraud_alerts(reviewed);

-- Grant permissions (adjust user as needed)
GRANT ALL PRIVILEGES ON call_records TO cdr_user;
GRANT ALL PRIVILEGES ON suspicious_patterns TO cdr_user;
GRANT ALL PRIVILEGES ON sentinel_fraud_alerts TO cdr_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cdr_user;
