targets:
  $default:
    builders:
      ferry_generator|gql_build:
        enabled: true
        options:
          schema: acm_mobile|lib/graphql/schema.graphql
          output_dir: lib/graphql/__generated__
          
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: acm_mobile|lib/graphql/schema.graphql
          output_dir: lib/graphql/__generated__
          
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: acm_mobile|lib/graphql/schema.graphql
          output_dir: lib/graphql/__generated__

      riverpod_generator:
        enabled: true
        options:
          provider_name_prefix: ""
          
      freezed:
        enabled: true
        options:
          format: true
          
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          include_if_null: false
          
      injectable_generator:injectable_builder:
        enabled: true
