
#!/usr/bin/env python3
"""
Market Research Scanner
Fetches Google Trends RSS feed and generates a daily briefing report.
"""

import requests
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path


def fetch_trends_rss(geo='NG'):
    """
    Fetch Google Trends RSS feed for a specific geography.

    Args:
        geo: Country code (default: 'NG' for Nigeria)

    Returns:
        XML string content
    """
    url = f'https://trends.google.com/trends/trendingsearches/daily/rss?geo={geo}'
    response = requests.get(url, timeout=10)
    response.raise_for_status()
    return response.text


def parse_trending_topics(xml_content, limit=3):
    """
    Parse XML content to extract trending topics.

    Args:
        xml_content: XML string from RSS feed
        limit: Number of top topics to extract (default: 3)

    Returns:
        List of dictionaries with topic information
    """
    root = ET.fromstring(xml_content)
    topics = []

    # Find all items in the RSS feed
    for item in root.findall('.//item')[:limit]:
        title = item.find('title')
        description = item.find('description')
        link = item.find('link')
        pub_date = item.find('pubDate')

        # Extract traffic volume if available
        traffic = item.find('.//{http://www.google.com/trends/trendingsearches}approx_traffic')

        topic = {
            'title': title.text if title is not None else 'N/A',
            'description': description.text if description is not None else 'N/A',
            'link': link.text if link is not None else 'N/A',
            'pub_date': pub_date.text if pub_date is not None else 'N/A',
            'traffic': traffic.text if traffic is not None else 'N/A'
        }
        topics.append(topic)

    return topics


def generate_markdown_report(topics, geo='Nigeria'):
    """
    Generate a markdown report from trending topics.

    Args:
        topics: List of topic dictionaries
        geo: Geographic location name

    Returns:
        Markdown formatted string
    """
    today = datetime.now().strftime('%Y-%m-%d')

    report = f"""# Daily Market Research Briefing
**Date:** {today}
**Region:** {geo}
**Source:** Google Trends

## Top Trending Topics

"""

    for i, topic in enumerate(topics, 1):
        report += f"### {i}. {topic['title']}\n\n"

        if topic['traffic'] != 'N/A':
            report += f"**Approximate Traffic:** {topic['traffic']}\n\n"

        if topic['description'] != 'N/A':
            # Clean up description HTML if present
            desc = topic['description'].replace('<b>', '**').replace('</b>', '**')
            report += f"{desc}\n\n"

        if topic['link'] != 'N/A':
            report += f"[More Information]({topic['link']})\n\n"

        report += "---\n\n"

    report += f"""
## Analysis Notes

*This report was automatically generated by the market_scan.py script on {today}.*

## Next Steps

- Review trending topics for relevance to mobile gaming market
- Identify potential opportunities or threats
- Cross-reference with competitive intelligence
"""

    return report


def save_report(report, output_path='docs/product/research/daily_briefing.md'):
    """
    Save the markdown report to a file.

    Args:
        report: Markdown content string
        output_path: Path to save the report
    """
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report)

    print(f"Report saved to: {output_path}")


def main():
    """Main execution function."""
    try:
        print("Fetching Google Trends RSS feed for Nigeria...")
        xml_content = fetch_trends_rss(geo='NG')

        print("Parsing trending topics...")
        topics = parse_trending_topics(xml_content, limit=3)

        print(f"Found {len(topics)} trending topics")

        print("Generating markdown report...")
        report = generate_markdown_report(topics, geo='Nigeria')

        print("Saving report...")
        save_report(report)

        print("Daily briefing generated successfully!")

    except requests.RequestException as e:
        print(f"Error fetching RSS feed: {e}")
        return 1
    except ET.ParseError as e:
        print(f"Error parsing XML: {e}")
        return 1
    except Exception as e:
        print(f"Unexpected error: {e}")
        return 1

    return 0


if __name__ == '__main__':
    exit(main())
