# ============================================================================
# Anti-Call Masking Platform - Kubernetes Deployment
# Detection Engine Deployment and Service
# Version: 2.0 | Date: 2026-01-22
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: acm
  labels:
    app.kubernetes.io/name: anti-call-masking
    app.kubernetes.io/component: platform

---
# ConfigMap for ACM Detection Engine
apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-engine-config
  namespace: acm
data:
  # Detection thresholds
  ACM_CPM_WARNING: "40"
  ACM_CPM_CRITICAL: "60"
  ACM_ACD_WARNING: "10"
  ACM_ACD_CRITICAL: "5"
  ACM_UNIQUE_DEST_WARNING: "100"
  ACM_UNIQUE_DEST_CRITICAL: "200"
  
  # Server config
  ACM_HOST: "0.0.0.0"
  ACM_PORT: "8080"
  ACM_METRICS_PORT: "9090"
  
  # Logging
  RUST_LOG: "info,acm_detection=debug"
  RUST_BACKTRACE: "0"

---
# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: acm-engine-secrets
  namespace: acm
type: Opaque
stringData:
  # Database credentials (replace with actual values)
  YUGABYTE_URL: "postgres://opensips:acm_secure_2026@yugabyte.acm.svc.cluster.local:5433/opensips"
  CLICKHOUSE_URL: "http://clickhouse.acm.svc.cluster.local:8123"
  DRAGONFLY_URL: "redis://dragonfly.acm.svc.cluster.local:6379"
  
  # NCC credentials
  NCC_CLIENT_ID: ""
  NCC_CLIENT_SECRET: ""
  NCC_ICL_LICENSE: ""

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acm-detection-engine
  namespace: acm
  labels:
    app: acm-detection-engine
    app.kubernetes.io/name: acm-detection-engine
    app.kubernetes.io/component: detection
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: acm-detection-engine
  template:
    metadata:
      labels:
        app: acm-detection-engine
        app.kubernetes.io/name: acm-detection-engine
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: acm-engine
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      
      # Anti-affinity to spread across nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: acm-detection-engine
                topologyKey: kubernetes.io/hostname
        
        # Prefer nodes with SSD
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - c5.xlarge
                      - c5.2xlarge
                      - c6i.xlarge
      
      # Topology spread for multi-AZ
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: acm-detection-engine
      
      containers:
        - name: detection-engine
          image: acm/detection-engine:2.0
          imagePullPolicy: Always
          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          
          envFrom:
            - configMapRef:
                name: acm-engine-config
            - secretRef:
                name: acm-engine-secrets
          
          env:
            - name: ACM_REGION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['topology.kubernetes.io/zone']
            - name: ACM_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "4Gi"
          
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      
      volumes:
        - name: tmp
          emptyDir: {}
      
      terminationGracePeriodSeconds: 30

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: acm-detection-engine
  namespace: acm
  labels:
    app: acm-detection-engine
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app: acm-detection-engine

---
# Headless Service for internal discovery
apiVersion: v1
kind: Service
metadata:
  name: acm-detection-engine-headless
  namespace: acm
  labels:
    app: acm-detection-engine
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: acm-detection-engine

---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: acm-detection-engine
  namespace: acm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acm-detection-engine
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 2
          periodSeconds: 120

---
# PodDisruptionBudget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: acm-detection-engine
  namespace: acm
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: acm-detection-engine

---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acm-engine
  namespace: acm

---
# Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: acm-detection-engine
  namespace: acm
spec:
  podSelector:
    matchLabels:
      app: acm-detection-engine
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        # Allow from OpenSIPS pods
        - podSelector:
            matchLabels:
              app: opensips
        # Allow from management API
        - podSelector:
            matchLabels:
              app: acm-management-api
        # Allow from Prometheus
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9090
  egress:
    - to:
        # Allow to DragonflyDB
        - podSelector:
            matchLabels:
              app: dragonfly
      ports:
        - protocol: TCP
          port: 6379
    - to:
        # Allow to YugabyteDB
        - podSelector:
            matchLabels:
              app: yugabyte
      ports:
        - protocol: TCP
          port: 5433
    - to:
        # Allow to ClickHouse
        - podSelector:
            matchLabels:
              app: clickhouse
      ports:
        - protocol: TCP
          port: 8123
    - to:
        # Allow to NCC API (external)
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
