---
# Secret for sensitive configuration
# NOTE: In production, use external secret management (Vault, AWS Secrets Manager, etc.)
apiVersion: v1
kind: Secret
metadata:
  name: fraud-detection-secrets
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Switch authentication (base64 encode in production)
  SWITCH_PASSWORD: "CHANGE_ME_IN_PRODUCTION"

  # Webhook URLs for alerting
  SLACK_WEBHOOK_URL: ""
  PAGERDUTY_API_KEY: ""

  # kdb+ license (mount as file in production)
  # KDB_LICENSE: ""
